language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.1
  - ruby-head
  - rbx

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

script: bundle exec rake test
